packages:
  - ./site
  - ./packages/*
  - ./tools

allowBuilds:
  '@sentry/cli': true
  esbuild: true
  sharp: true
  supabase: true

onlyBuiltDependencies:
  - "@sentry/cli"
  - esbuild
  - sharp
  - supabase
