// THIS FILE IS AUTO-GENERATED by scripts/generate-markdown-index.ts
// DO NOT EDIT BY HAND

export const API_INDEX = {
	routes: ["get-route", "get-route-group", "get-route-groups"],
	shapes: ["get-shape"],
	trips: ["get-trip", "get-trips"],
} as const;

export type ApiObject = keyof typeof API_INDEX;
export type ApiMethod<T extends ApiObject> = (typeof API_INDEX)[T][number];

// Handy helper types:
export type AnyApiMethod = ApiMethod<ApiObject>;
