// THIS FILE IS AUTO-GENERATED by scripts/generate-markdown-index.ts
// DO NOT EDIT BY HAND

export const API_INDEX = {
	routes: ["get-route", "get-route-group", "get-route-groups"],
	"service-alerts": ["get-service-alert", "get-service-alerts"],
	shapes: ["get-shape"],
	stops: ["get-stop", "get-stop-departures", "get-stop-routes", "get-stop-schedule", "get-stop-trips", "get-stops"],
	trips: ["get-trip", "get-trips"],
	vehicles: ["get-vehicle", "get-vehicle-location", "get-vehicles"],
} as const;

export type ApiObject = keyof typeof API_INDEX;
export type ApiMethod<T extends ApiObject> = (typeof API_INDEX)[T][number];

// Handy helper types:
export type AnyApiMethod = ApiMethod<ApiObject>;
