import { exec } from "node:child_process";
import { readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { promisify } from "node:util";

const execAsync = promisify(exec);

const ROOT = join(process.cwd(), "src", "content", "api");
const OUT_FILE = join(process.cwd(), "src", "types", "md.generated.ts");

async function main() {
	// top-level objects (folders under src/app/markdown)
	const topEntries = await readdir(ROOT, { withFileTypes: true });
	const objects = topEntries
		.filter((e) => e.isDirectory())
		.map((e) => e.name)
		.sort((a, b) => a.localeCompare(b));

	const index: Record<string, string[]> = {};

	for (const obj of objects) {
		const objectPath = join(ROOT, obj);

		// method folders under each object
		const methodEntries = await readdir(objectPath, { withFileTypes: true });
		const methods = methodEntries
			.filter((e) => e.isDirectory())
			.map((e) => e.name)
			.sort((a, b) => a.localeCompare(b));

		index[obj] = methods;
	}

	const fileContents = `// THIS FILE IS AUTO-GENERATED by scripts/generate-markdown-index.ts
// DO NOT EDIT BY HAND

export const API_INDEX = ${JSON.stringify(index, null, 2)} as const;

export type ApiObject = keyof typeof API_INDEX;
export type ApiMethod<T extends ApiObject> = (typeof API_INDEX)[T][number];

// Handy helper types:
export type AnyApiMethod = ApiMethod<ApiObject>;
`;

	await writeFile(OUT_FILE, fileContents, "utf8");
	console.log(`✅ Generated: ${OUT_FILE}`);

	// Format the generated file with biome
	try {
		await execAsync(`pnpm exec biome format --write ${OUT_FILE}`);
		console.log(`✅ Formatted: ${OUT_FILE}`);
	} catch (error) {
		console.warn(`⚠️  Failed to format ${OUT_FILE}:`, error);
	}
}

main().catch((err) => {
	console.error("❌ Failed to generate markdown index:", err);
	process.exit(1);
});
